// Static seed data: default rooms, default assets, and Trimark service history

const defaultCategories=[
  {name:'HVAC',icon:'❄️'},
  {name:'Kitchen',icon:'🍳'},
  {name:'Safety',icon:'🚒'},
  {name:'AV & Tech',icon:'📽️'},
  {name:'Liturgical',icon:'⛪'},
  {name:'Grounds',icon:'🌿'},
  {name:'Plumbing',icon:'🔧'},
  {name:'Electrical',icon:'💡'},
  {name:'Other',icon:'📦'},
];

const defaultRooms={
  'Church':[
    {name:'Nave',floor:'Main',notes:'Main worship space'},
    {name:'Sanctuary',floor:'Main',notes:'Trane RTU serves this space'},
    {name:'Choir Loft',floor:'Main',notes:'AHU 14 overhead'},
    {name:'Upper Sacristy',floor:'Main',notes:''},
    {name:'Lower Sacristy',floor:'Main',notes:'Zone sensor relocated here'},
    {name:'Narthex',floor:'Main',notes:'Entrance vestibule'},
    {name:'Chapel',floor:'Main',notes:'AHU 13'},
    {name:'Confessionals',floor:'Main',notes:'Fujitsu split units'},
    {name:"Men's Room",floor:'Main',notes:'AHU 12 in ceiling'},
    {name:"Women's Room",floor:'Main',notes:''},
    {name:"Janitor's Closet",floor:'Main',notes:''},
    {name:'Mechanical Room',floor:'Main',notes:''},
    {name:'Office Entry',floor:'Main',notes:''},
    {name:'Business Manager Office',floor:'Main',notes:''},
    {name:"Amy's Office 105A",floor:'Main',notes:'LG cassette — key needed for PM access'},
    {name:'Conference Room',floor:'Main',notes:''},
    {name:'Copy Room',floor:'Main',notes:''},
    {name:'Storage Room',floor:'Main',notes:''},
    {name:'Music Director Office',floor:'Main',notes:''},
    {name:'Associate Office',floor:'Main',notes:''},
    {name:'Pastor Office',floor:'Main',notes:''},
    {name:'Mini Kitchen',floor:'Main',notes:''},
    {name:'Knights Hall',floor:'Lower Level',notes:'Cassette 8A serves this area'},
    {name:'Knights Kitchen',floor:'Lower Level',notes:'Full commercial kitchen'},
    {name:'Knights Bathroom',floor:'Lower Level',notes:''},
    {name:'Storage Room (Lower)',floor:'Lower Level',notes:'Refrigerator and freezer'},
  ],
  'Education Center':[
    {name:'Vestibule',floor:'1st Floor',notes:''},
    {name:'Lobby 102',floor:'1st Floor',notes:''},
    {name:'Library 103',floor:'1st Floor',notes:'LG cassette ceiling'},
    {name:'Storage 103A',floor:'1st Floor',notes:''},
    {name:'Workroom 104',floor:'1st Floor',notes:'LG cassette'},
    {name:'RE Admin Office 105',floor:'1st Floor',notes:'LG cassette'},
    {name:'RE Director 105B',floor:'1st Floor',notes:'LG cassette'},
    {name:'Youth Ministry 105C',floor:'1st Floor',notes:'LG cassette'},
    {name:'Meeting Room 105A',floor:'1st Floor',notes:'LG — Amy has key'},
    {name:'Classroom 107',floor:'1st Floor',notes:'LG cassette'},
    {name:'Classroom 108',floor:'1st Floor',notes:''},
    {name:'Classroom 113',floor:'1st Floor',notes:'LG cassette'},
    {name:'Janitor Storage 114',floor:'1st Floor',notes:''},
    {name:'Fire Pump 114A',floor:'1st Floor',notes:'Ed Center fire pump'},
    {name:'Janitor Closet 109',floor:'1st Floor',notes:''},
    {name:'Mechanical 110',floor:'1st Floor',notes:''},
    {name:'Multi-Purpose Entry 115',floor:'1st Floor',notes:''},
    {name:'Multi-Purpose Hall 116',floor:'1st Floor',notes:'Large event space'},
    {name:'Kitchen 118',floor:'1st Floor',notes:'Full commercial kitchen · LG FCU #3'},
    {name:'Storage 120',floor:'1st Floor',notes:''},
    {name:"Men's Room 1st Floor",floor:'1st Floor',notes:''},
    {name:"Women's Room 1st Floor",floor:'1st Floor',notes:''},
    {name:'Staff Bath 1st Floor',floor:'1st Floor',notes:''},
    {name:'Stair A',floor:'1st Floor',notes:''},
    {name:'Classroom 201',floor:'2nd Floor',notes:'LG unit'},
    {name:'Classroom 202',floor:'2nd Floor',notes:'LG unit'},
    {name:'Classroom 204',floor:'2nd Floor',notes:'LG — fan motor issue'},
    {name:'Classroom 205',floor:'2nd Floor',notes:'LG unit'},
    {name:'Classroom 206',floor:'2nd Floor',notes:'LG unit'},
    {name:'Classroom 207',floor:'2nd Floor',notes:'LG unit'},
    {name:'Classroom 208',floor:'2nd Floor',notes:'LG unit'},
    {name:'Classroom 209',floor:'2nd Floor',notes:''},
    {name:'Classroom 210',floor:'2nd Floor',notes:'LG unit'},
    {name:'Classroom 213',floor:'2nd Floor',notes:'LG unit'},
    {name:'Storage Closet 213A',floor:'2nd Floor',notes:''},
    {name:'Storage Closet 214',floor:'2nd Floor',notes:''},
    {name:'Janitor Closet 203',floor:'2nd Floor',notes:''},
    {name:'Roof ST03',floor:'Roof',notes:''},
    {name:'Staff Bath 2nd Floor',floor:'2nd Floor',notes:'LG FCU #4'},
    {name:"Men's Room 2nd Floor",floor:'2nd Floor',notes:''},
    {name:"Women's Room 2nd Floor",floor:'2nd Floor',notes:''},
  ],
  'Rectory':[
    {name:'Pastor Bedroom',floor:'Upper',notes:''},
    {name:'Upper Bedroom',floor:'Upper',notes:''},
    {name:'Guest Room 1',floor:'Upper',notes:''},
    {name:'Guest Room 2',floor:'Upper',notes:''},
    {name:'Kitchen',floor:'Main',notes:''},
    {name:'Dining Room',floor:'Main',notes:''},
    {name:'Family Room',floor:'Main',notes:''},
    {name:'Laundry Room',floor:'Main',notes:''},
    {name:'Utility Closet',floor:'Main',notes:'AHU-1 and AHU-2 units'},
    {name:'Front Porch',floor:'Exterior',notes:''},
    {name:'Back Deck',floor:'Exterior',notes:'HP units on back wall'},
  ],
};

const defaultAssets=[
  {serial:'10125RYN2F',description:'Heat Pump',size:'3 Ton',location:'Rectory — back of house',room_number:'Utility Closet',manufacturer:'American Standard',expected_life:'15 yrs',building:'Rectory',category:'HVAC',status:'Active',notes:''},
  {serial:'101642AX1V',description:'AHU-1',size:'',location:'Rectory — utility closet',room_number:'Utility Closet',manufacturer:'American Standard',expected_life:'15 yrs',building:'Rectory',category:'HVAC',status:'Active',notes:''},
  {serial:'12082KEN4F',description:'HP 2',size:'',location:'Rectory — back wall',room_number:'Back Deck',manufacturer:'American Standard',expected_life:'15 yrs',building:'Rectory',category:'HVAC',status:'Active',notes:'Low refrigerant history. Core valve leaks repaired May 2022.'},
  {serial:'11502H9HAV',description:'AHU #2',size:'',location:'Rectory — right wall',room_number:'Utility Closet',manufacturer:'American Standard',expected_life:'15 yrs',building:'Rectory',category:'HVAC',status:'Active',notes:''},
  {serial:'C11H04914',description:'40 Ton Package Unit (RTU)',size:'40 Ton',location:'Church — ground outside',room_number:'Exterior',manufacturer:'Trane',expected_life:'15 yrs',building:'Church',category:'HVAC',status:'Maintenance',notes:'Recurring: humidity, compressor replaced 2020, RTOM board faulty 2023. Heat exchanger replacement pending ($16,080 bid Oct 2023).'},
  {serial:'KYA016198',description:'Fan Coil — Confessional Left',size:'',location:'Church — confessional ceiling left',room_number:'Confessionals',manufacturer:'Fujitsu',expected_life:'20 yrs',building:'Church',category:'HVAC',status:'Active',notes:'Register boot reattached Oct 2022.'},
  {serial:'KYA016480',description:'Fan Coil — Confessional Right',size:'',location:'Church — confessional ceiling right',room_number:'Confessionals',manufacturer:'Fujitsu',expected_life:'20 yrs',building:'Church',category:'HVAC',status:'Active',notes:''},
  {serial:'101650D11V',description:'AHU 10',size:'3 Ton',location:'Church interior',room_number:'Mechanical Room',manufacturer:'American Standard',expected_life:'15 yrs',building:'Church',category:'HVAC',status:'Active',notes:'5A control fuse replaced Oct 2022.'},
  {serial:'9055N8S2V',description:'AHU 13',size:'3 Ton',location:'Church — chapel',room_number:'Chapel',manufacturer:'American Standard',expected_life:'15 yrs',building:'Church',category:'HVAC',status:'Active',notes:''},
  {serial:'90452U32V',description:'AHU 14',size:'3 Ton',location:'Church — choir loft closet',room_number:'Choir Loft',manufacturer:'American Standard',expected_life:'15 yrs',building:'Church',category:'HVAC',status:'Active',notes:''},
  {serial:'102446631V',description:'AHU 12',size:'3 Ton',location:"Church — men's bath ceiling",room_number:"Men's Room",manufacturer:'American Standard',expected_life:'15 yrs',building:'Church',category:'HVAC',status:'Active',notes:''},
  {serial:'HSN009612',description:'Heat Pump Unit #6',size:'',location:'Church — ground outside',room_number:'Exterior',manufacturer:'Fujitsu',expected_life:'20 yrs',building:'Church',category:'HVAC',status:'Active',notes:'Blown fuse & damaged AC/DC converter chip Dec 2020. Board replaced.'},
  {serial:'HSA010006',description:'Cassette 6 — Church Office',size:'',location:'Church office',room_number:"Amy's Office 105A",manufacturer:'Fujitsu',expected_life:'20 yrs',building:'Church',category:'HVAC',status:'Active',notes:'Access requires key from Amy.'},
  {serial:'GSA005025',description:'Cassette 8A — Knights Hall',size:'',location:'Church lower level',room_number:'Knights Hall',manufacturer:'Fujitsu',expected_life:'20 yrs',building:'Church',category:'HVAC',status:'Maintenance',notes:'INSTALLED 1995 — near end of life. Recurring communication faults. Recommend replacement.'},
  {serial:'GSA005548',description:'Cassette 8B',size:'',location:'Church — ground outside',room_number:'Exterior',manufacturer:'Fujitsu',expected_life:'20 yrs',building:'Church',category:'HVAC',status:'Active',notes:''},
  {serial:'201306-BNEW08714',description:'RTU 1',size:'',location:'Ed Center — rooftop',room_number:'Roof ST03',manufacturer:'AAON',expected_life:'—',building:'Education Center',category:'HVAC',status:'Active',notes:'Smoke detector alarm issues Dec 2020 & Jul 2022.'},
  {serial:'201306-BNET08710',description:'RTU 2',size:'',location:'Ed Center — rooftop',room_number:'Roof ST03',manufacturer:'AAON',expected_life:'—',building:'Education Center',category:'HVAC',status:'Active',notes:''},
  {serial:'303KALC00048',description:'Heat Recovery Unit 1a',size:'',location:'Ed Center — rooftop',room_number:'Roof ST03',manufacturer:'LG',expected_life:'—',building:'Education Center',category:'HVAC',status:'Active',notes:''},
  {serial:'301KABF00021',description:'Heat Recovery Unit 2',size:'',location:'Ed Center — rooftop',room_number:'Roof ST03',manufacturer:'LG',expected_life:'—',building:'Education Center',category:'HVAC',status:'Active',notes:'Full compressor & inverter board replacement Jul 2022 ($11,368).'},
  {serial:'302KARW00006',description:'Heat Recovery Unit 1',size:'',location:'Ed Center — rooftop',room_number:'Roof ST03',manufacturer:'LG',expected_life:'—',building:'Education Center',category:'HVAC',status:'Active',notes:''},
  {serial:'303KAWQ00009',description:'Heat Recovery Unit 4a',size:'',location:'Ed Center — rooftop',room_number:'Roof ST03',manufacturer:'LG',expected_life:'—',building:'Education Center',category:'HVAC',status:'Active',notes:''},
  {serial:'303KAZK00045',description:'Heat Recovery Unit 3',size:'',location:'Ed Center — rooftop',room_number:'Roof ST03',manufacturer:'LG',expected_life:'—',building:'Education Center',category:'HVAC',status:'Active',notes:''},
  {serial:'143SE96414-1',description:'Exhaust Fan #1',size:'',location:'Ed Center — rooftop',room_number:'Roof ST03',manufacturer:'Loren Cook',expected_life:'—',building:'Education Center',category:'HVAC',status:'Active',notes:'Belt A22.'},
  {serial:'143SE96414-2',description:'Exhaust Fan #2',size:'',location:'Ed Center — rooftop',room_number:'Roof ST03',manufacturer:'Loren Cook',expected_life:'—',building:'Education Center',category:'HVAC',status:'Active',notes:'Motor bearing replaced. 20A fuse installed May 2022.'},
  {serial:'143SE96414-3',description:'Exhaust Fan #3',size:'',location:'Ed Center — rooftop',room_number:'Roof ST03',manufacturer:'Loren Cook',expected_life:'—',building:'Education Center',category:'HVAC',status:'Active',notes:'Belt 4L210.'},
  {serial:'TBD-EF4',description:'Exhaust Fan #4',size:'',location:'Ed Center — kitchen side wall',room_number:'Kitchen 118',manufacturer:'Loren Cook',expected_life:'—',building:'Education Center',category:'HVAC',status:'Active',notes:''},
  {serial:'303KAJP00204',description:'Cassette — Classroom 204',size:'',location:'Ed Center — classroom 204',room_number:'Classroom 204',manufacturer:'LG',expected_life:'—',building:'Education Center',category:'HVAC',status:'Maintenance',notes:'Fan motor bearing squealing Oct 2022 — motor needs replacement.'},
  // Kitchen assets
  {serial:'',description:'Fryer #1',size:'',location:'Kitchen 118',room_number:'Kitchen 118',manufacturer:'',expected_life:'',building:'Education Center',category:'Kitchen',status:'Active',notes:''},
  {serial:'',description:'Fryer #2',size:'',location:'Kitchen 118',room_number:'Kitchen 118',manufacturer:'',expected_life:'',building:'Education Center',category:'Kitchen',status:'Active',notes:''},
  {serial:'',description:'Double Freezer',size:'',location:'Kitchen 118',room_number:'Kitchen 118',manufacturer:'',expected_life:'',building:'Education Center',category:'Kitchen',status:'Active',notes:''},
  {serial:'',description:'Double Refrigerator',size:'',location:'Kitchen 118',room_number:'Kitchen 118',manufacturer:'',expected_life:'',building:'Education Center',category:'Kitchen',status:'Active',notes:''},
  {serial:'',description:'Ice Maker',size:'',location:'Kitchen 118',room_number:'Kitchen 118',manufacturer:'',expected_life:'',building:'Education Center',category:'Kitchen',status:'Active',notes:''},
  {serial:'',description:'Coffee Maker',size:'',location:'Kitchen 118',room_number:'Kitchen 118',manufacturer:'',expected_life:'',building:'Education Center',category:'Kitchen',status:'Active',notes:''},
  {serial:'',description:'Double Oven & Griddle Stovetop',size:'',location:'Kitchen 118',room_number:'Kitchen 118',manufacturer:'',expected_life:'',building:'Education Center',category:'Kitchen',status:'Active',notes:''},
  {serial:'',description:'Single Stovetop Oven',size:'',location:'Kitchen 118',room_number:'Kitchen 118',manufacturer:'',expected_life:'',building:'Education Center',category:'Kitchen',status:'Active',notes:''},
  {serial:'',description:'Hood — Kitchen 118',size:'',location:'Kitchen 118',room_number:'Kitchen 118',manufacturer:'',expected_life:'',building:'Education Center',category:'Kitchen',status:'Active',notes:''},
  {serial:'',description:'Warming Cabinet #1',size:'',location:'Kitchen 118',room_number:'Kitchen 118',manufacturer:'',expected_life:'',building:'Education Center',category:'Kitchen',status:'Active',notes:''},
  {serial:'',description:'Warming Cabinet #2',size:'',location:'Kitchen 118',room_number:'Kitchen 118',manufacturer:'',expected_life:'',building:'Education Center',category:'Kitchen',status:'Active',notes:''},
  {serial:'',description:'Double Refrigerator',size:'',location:'Knights Kitchen',room_number:'Knights Kitchen',manufacturer:'',expected_life:'',building:'Church',category:'Kitchen',status:'Active',notes:''},
  {serial:'',description:'Oven with Stovetop & Griddle',size:'',location:'Knights Kitchen',room_number:'Knights Kitchen',manufacturer:'',expected_life:'',building:'Church',category:'Kitchen',status:'Active',notes:''},
  {serial:'',description:'Triple Sink',size:'',location:'Knights Kitchen',room_number:'Knights Kitchen',manufacturer:'',expected_life:'',building:'Church',category:'Kitchen',status:'Active',notes:''},
  {serial:'',description:'Disposal',size:'',location:'Knights Kitchen',room_number:'Knights Kitchen',manufacturer:'',expected_life:'',building:'Church',category:'Kitchen',status:'Active',notes:''},
  {serial:'',description:'Hood — Knights Kitchen',size:'',location:'Knights Kitchen',room_number:'Knights Kitchen',manufacturer:'',expected_life:'',building:'Church',category:'Kitchen',status:'Active',notes:''},
  {serial:'',description:'Oven — Knights Kitchen',size:'',location:'Knights Kitchen',room_number:'Knights Kitchen',manufacturer:'',expected_life:'',building:'Church',category:'Kitchen',status:'Active',notes:''},
  {serial:'',description:'Double Refrigerator — Lower Storage',size:'',location:'Lower Level Storage Room',room_number:'Storage Room (Lower)',manufacturer:'',expected_life:'',building:'Church',category:'Kitchen',status:'Active',notes:''},
  {serial:'',description:'Single Freezer — Lower Storage',size:'',location:'Lower Level Storage Room',room_number:'Storage Room (Lower)',manufacturer:'',expected_life:'',building:'Church',category:'Kitchen',status:'Active',notes:''},
  {serial:'',description:'Single Refrigerator — Lower Storage',size:'',location:'Lower Level Storage Room',room_number:'Storage Room (Lower)',manufacturer:'',expected_life:'',building:'Church',category:'Kitchen',status:'Active',notes:''},
];

const serviceHistory=[
  {inv:'118436',date:'09/09/2020',desc:'Trane RTU diagnosis — Compressor #1 tripped, zone sensor mislocated. Recommend new compressor, relocate zone sensor to sanctuary.',equip:'Trane RTU C11H04914',building:'Church',amount:238},
  {inv:'118472',date:'09/17/2020',desc:'Replace compressor #1, leak search circuit #2, relocate zone sensor, install temp/humidity sensors in sanctuary. New compressor & filter drier installed, recharged 19.4 lbs R410a.',equip:'Trane RTU C11H04914',building:'Church',amount:10660},
  {inv:'118502',date:'09/21/2020',desc:'Rectory heat pump — thermostat error CH-29. Compressor over amperage. Cleaned coils, reset system.',equip:'HP 10125RYN2F',building:'Rectory',amount:595},
  {inv:'118785',date:'11/30/2020',desc:'September PM — All buildings. Cassette 6 communication fault. EF1 belt broken, EF2 motor bearing failing.',equip:'All units',building:'Education Center',amount:3487},
  {inv:'119156',date:'11/30/2020',desc:'Classroom thermostats CH29 — checked all 10, reset all, working fine.',equip:'Classroom thermostats',building:'Education Center',amount:238},
  {inv:'119232',date:'12/15/2020',desc:'Cassette 6 church office — replaced blown 3.15A fuse. Damaged AC/DC converter chip found.',equip:'HP6 HSN009612 / Cassette 6 HSA010006',building:'Church',amount:595},
  {inv:'119526',date:'12/15/2020',desc:'Installed humidifier — cut ductwork, mounted humidifier & bypass, wired humidistat.',equip:'Humidifier',building:'Church',amount:1988},
  {inv:'119538',date:'12/31/2020',desc:'Replaced control board on HP 6 condenser. Faulty indoor PCB and condenser fan motor still causing issues.',equip:'Fujitsu HP6 HSN009612',building:'Church',amount:1024.50},
  {inv:'119632',date:'12/31/2020',desc:'School RTUs offline — smoke detector alarm triggered by construction debris. Reset alarms.',equip:'AAON RTU 201306-BNEW08714',building:'Education Center',amount:297.50},
  {inv:'124159',date:'01/28/2022',desc:'Fall PM — all units running. Deficiency: Cassette 8A not functioning.',equip:'All units',building:'Church',amount:3487},
  {inv:'125975',date:'05/27/2022',desc:'Replaced RTU thermostat with Honeywell 8000 2h/2c with remote sensor terminals.',equip:'Trane RTU C11H04914',building:'Church',amount:1106},
  {inv:'126095',date:'05/27/2022',desc:'Rectory HP2 — core valves leaking. Replaced 2 core valves, added 7 lbs 8 oz R410a.',equip:'HP 2 12082KEN4F',building:'Rectory',amount:1000.50},
  {inv:'126760',date:'07/29/2022',desc:'Heat Recovery Unit 2 — compressor & PCB replacement. System pressurized 24hr test.',equip:'LG HR Unit 2 301KABF00021',building:'Education Center',amount:11368},
  {inv:'127057',date:'06/30/2022',desc:'Church RTU — humidity 95%. Reset economizer, restarted. Humidity dropped to 65%.',equip:'Trane RTU C11H04914',building:'Church',amount:500},
  {inv:'128675',date:'10/13/2022',desc:'Church RTU humidity — setpoint corrected. Adjusted RTOM to ~45%.',equip:'Trane RTU C11H04914',building:'Church',amount:375},
  {inv:'128701',date:'10/13/2022',desc:'AHU 10 — blown 5A fuse. Replaced 3A fuse, system running at 0.8A.',equip:'AHU 10 101650D11V',building:'Church',amount:140},
  {inv:'128702',date:'10/13/2022',desc:'Cassette #21 classroom 204 — fan motor bearing squealing. Motor needs replacement.',equip:'LG Cassette 303KAJP00204',building:'Education Center',amount:125},
  {inv:'131642',date:'08/17/2023',desc:'Trane RTU not cooling Sunday service. RTOM board and humidity sensor faulty. Recommend replacement.',equip:'Trane RTU C11H04914',building:'Church',amount:0},
  {inv:'BID-Oct2023',date:'10/04/2023',desc:'PROPOSAL: Heat exchanger replacement on Trane RTU. Disassemble, install new exchangers with boom truck, test.',equip:'Trane RTU C11H04914',building:'Church',amount:16080},
];
